# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# Configuration for private hex repositories
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-private-registries

version: 2

registries:
  dependabot-private-repo:
    type: hex-repository
    repo: dependabot
    url: "https://dependabot-private.fly.dev"
    auth-key: d6fc2b6n6h7katic6vuq6k5e2csahcm4

updates:
  - package-ecosystem: "mix"
    directory: "/"
    insecure-external-code-execution: "allow"
    registries:
      - dependabot-private-repo
    schedule:
      interval: "daily"
