# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# Configuration for private hex repositories
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-private-registries

version: 2

registries:
  oban-private-repo:
    type: hex-repository
    repo: oban
    url: https://hexrepo.betterdoc.org
    auth-key: ${{ secrets.HEX_REPO_AUTH_KEY }}
    public-key-fingerprint: "SHA256:w9Qm2VfDiSbcN8dCUFPZqOP0HZfMqmnXAdUDBkkUkxk"

updates:
  - package-ecosystem: "mix"
    directory: "/"
    insecure-external-code-execution: "allow"
    registries:
      - oban-private-repo
    schedule:
      interval: "daily"

